#!/usr/bin/python

# Instructions
# Go into the 'src' folder
# Ensure that this file has execute permissions
# Usage: testpy <sqlfilename>
# Example testpy tpch1.sql

import datetime
import os
import sys

def createResultFolder():
    if not os.path.exists(os.path.join(os.getcwd(),'..','myresults',)):
        os.makedirs(os.path.join(os.getcwd(),'..','myresults',));

def setFilePaths(sqlFileName):
    resultFileName = sqlFileName.split(".")[0]+datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%s")+".dat"
    resultFile = os.path.join('..','myresults',resultFileName)
    binFolder = os.path.join('..','bin')
    jsqlJar = os.path.join('..','other','jsqlparser.jar')
    dataFolder = os.path.join('..','data','bigData')
    swapFolder = os.path.join('..','swapDir')
    sqlFile = os.path.join('..','data','bigData',sqlFileName)
    expectedFile = os.path.join('..','data','bigData',sys.argv[1].split(".")[0]+".expected.dat")

    return (binFolder, jsqlJar, dataFolder, swapFolder, sqlFile, resultFile, expectedFile)


def runCode(paths, withSwap):
    # print paths
    start_time = datetime.datetime.now()
    if withSwap:
        #print "with swap"
        os.system("java -cp "+paths[0]+":"+paths[1]+" edu.buffalo.cse562.Main --data /"+paths[2]+" --swap "+paths[3]+" /"+paths[4]+" > "+paths[5])
    else:
        #print "without swap"
        os.system("java -cp "+paths[0]+":"+paths[1]+" edu.buffalo.cse562.Main --data /"+paths[2]+" /"+paths[4]+" > "+paths[5])

    end_time = datetime.datetime.now()
    return start_time, end_time

def createSwapFolder():
    if not os.path.exists(os.path.join(os.getcwd(),'..','swapDir',)):
        os.makedirs(os.path.join(os.getcwd(),'..','swapDir',))

def compareFile(fp):
    try: 
        import filecmp
        print "Is the result generated and expected same? :",
        print filecmp.cmp(fp[5],fp[6])
    except:
        print "Unable to compare files"

def purgeSwapFolder():
    import shutil
    if not os.path.exists(os.path.join(os.getcwd(),'..','swapDir',)):
        shutil.rmtree(os.path.join(os.getcwd(),'..','swapDir',))

def printTimeDiff(times):
    diff = times[1]-times[0]
    print "Time taken for query evaluation: ",
    print diff
    print "In seconds: ",
    print diff.seconds
    # print diff.microseconds


if __name__=='__main__':
    createResultFolder()
    sqlFileName = sys.argv[1]
    if ('--no-swap' in sys.argv):
        withSwap = False
    else:
        withSwap = True
    print "For file: ", sqlFileName
    fp = setFilePaths(sqlFileName)
    purgeSwapFolder()
    createSwapFolder()
    # print fp
    printTimeDiff(runCode(fp,withSwap))
    compareFile(fp)
